### ISSUE TITLE
Crash with array in a sub-struct

### ISSUE THREAD

**Issue by BratishkaErik** [karlseguin/ztl#3]
Hello, I was porting [zig-ebuilder](https://github.com/BratishkaErik/zig-ebuilder) from `mustache-zig` to `ztl` yesterday and noticed some issues during it. My main blocker right now is this crash which occurs when I access two times any struct field with arrays inside. Here's small reduction:

```zig
const std = @import("std");
const ztl = @import("ztl");

pub fn main() !void {
    var gpa: std.heap.GeneralPurposeAllocator(.{}) = .{};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const array: []const []const u8 = &.{ "Hello", "World" };
    const globals = .{
        .report = .{
            .array = array,
        },
    };

    var template: ztl.Template(void) = .init(allocator, {});
    defer template.deinit();
    try template.compile(
        \\ <% @print(@report["array"]) %>
        // Any of these two crash it:
        \\ <% @print(@report["array"]) %>
        // \\ <% @print(@report) %>

        // This does not crash:
        // \\ <% @print(@report) %>
        // \\ <% @print(@report) %>
        // And this too:
        // \\ <% @print(@report) %>
        // \\ <% @print(@report["array"]) %>
    , .{});
    try template.render(
        std.io.null_writer, // or stdout, does not matter for crash
        globals,
        .{},
    );
}
```

It looks as if accessing subfield in global somehow overrides whole global.

Crash in Debug LLVM:
```
[Hello, World]
[Segmentation fault at address 0x10
/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/value.zig:34:17: 0x1072458 in write__anon_4857 (ztl)
        switch (self) {
                ^
/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/value.zig:47:39: 0x107313b in write__anon_4857 (ztl)
                    try items[0].write(writer, escape);
                                      ^
/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/vm.zig:516:61: 0x1078f0c in run__anon_3383 (ztl)
                                try items[start_index].write(stderr, false);
                                                            ^
/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/template.zig:99:23: 0x107be96 in render__anon_3049 (ztl)
            _ = vm.run(self.byte_code, writer) catch |runtime_err| {
                      ^
/home/bratishkaerik/reproduce-zig-libraries-bug/ztl/src/main.zig:30:24: 0x107c4d5 in main (ztl)
    try template.render(
                       ^
/usr/lib64/zig/9999/lib/std/start.zig:656:37: 0x105f9ea in posixCallMainAndExit (ztl)
            const result = root.main() catch |err| {
                                    ^
/usr/lib64/zig/9999/lib/std/start.zig:271:5: 0x105f59d in _start (ztl)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
[1]    187031 IOT instruction (core dumped)  zig-out/bin/ztl
```

Crash in Debug x86_64 (added because last information is different):
```
[Hello, World]
thread 187246 panic: switch on corrupt value
Unwind error at address `exe:0x10c954e` (error.AddressOutOfRange), trace may be incomplete

/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/value.zig:40:35: 0x1053575 in write__anon_4859 (ztl.zig)
            .ref => |ref| switch (ref.value) {
                                  ^
/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/vm.zig:516:61: 0x1059366 in run__anon_3384 (ztl.zig)
                                try items[start_index].write(stderr, false);
                                                            ^
/home/bratishkaerik/.cache/zig/p/12207dca7dfc207485323b41471e9a3f15e2d8dd75e721ef974e2e9fabedf977e676/src/template.zig:99:23: 0x105c4c4 in render__anon_3050 (ztl.zig)
            _ = vm.run(self.byte_code, writer) catch |runtime_err| {
                      ^
/home/bratishkaerik/reproduce-zig-libraries-bug/ztl/src/main.zig:30:24: 0x105c97d in main (main.zig)
    try template.render(
                       ^
/usr/lib64/zig/9999/lib/std/start.zig:656:37: 0x105cff8 in posixCallMainAndExit (std.zig)
            const result = root.main() catch |err| {
                                    ^
/usr/lib64/zig/9999/lib/std/start.zig:271:5: 0x1041016 in _start (std.zig)
    asm volatile (switch (native_arch) {
    ^
[1]    187246 IOT instruction (core dumped)  zig-out/bin/ztl
```

Disassemble:
```
// Version: 0
<main>:
0000 CONSTANT_STRING ` `
0005 OUTPUT
0006 GET_GLOBAL @0
0008 CONSTANT_STRING `array`
000d INDEX_GET
000e PRINT0010 CONSTANT_STRING `
 `
0015 OUTPUT
0016 GET_GLOBAL @0
0018 CONSTANT_STRING `array`
001d INDEX_GET
001e PRINT0020 CONSTANT_NULL
0021 RETURN
```

In my project it also appeared as `TypeError caused by: TypeError - Cannot index a list with a string key` in `foreach` loop, before I debugged it with `@print`

**Comment by karlseguin** [comment]
Thanks for the report. This should be fixed. The issue was that the INDEX_GET operation (i.e. doing a hash lookup) wasn't incrementing the reference count on the returned value. So when the RC was being decremented after the first print, it was being released prematurely.

**Comment by BratishkaErik** [comment]
Thanks for the fix. Unfortunately, it did not fixed my crash in the program, probably because it's more nester and also has struct-array-struct relationship. Can I ask you for help here? https://github.com/BratishkaErik/zig-ebuilder/pull/8

**Comment by karlseguin** [comment]
For the time being, I've disabled the referencing counting. There will not be a leak, since the entire render happens within an arena, but the peak memory usage during rendering could be slightly higher.

It's clearly buggy and I have a hard time reasoning about the current implementation. I want to redo it. In the meantime, disabling it entirely should solve any of these issues.

**Comment by BratishkaErik** [comment]
Thanks, everything seems to work fine now!
